apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: homepage-dev

bases:
  - ../../base

patchesStrategicMerge:
  - ingress-patch.yaml

images:
  - name: ghcr.io/vikingthedev/homepage-backend
    newTag: dev
  - name: ghcr.io/vikingthedev/homepage-frontend
    newTag: dev

replicas:
  - name: backend
    count: 1
  - name: frontend
    count: 1

configMapGenerator:
  - name: environment
    literals:
      - ENVIRONMENT=development
